/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SimultaneousequationcannoncalculatorIndexImport } from './routes/simultaneous_equation_cannon_calculator/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SimultaneousequationcannoncalculatorIndexRoute =
  SimultaneousequationcannoncalculatorIndexImport.update({
    id: '/simultaneous_equation_cannon_calculator/',
    path: '/simultaneous_equation_cannon_calculator/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/simultaneous_equation_cannon_calculator/': {
      id: '/simultaneous_equation_cannon_calculator/'
      path: '/simultaneous_equation_cannon_calculator'
      fullPath: '/simultaneous_equation_cannon_calculator'
      preLoaderRoute: typeof SimultaneousequationcannoncalculatorIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simultaneous_equation_cannon_calculator': typeof SimultaneousequationcannoncalculatorIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simultaneous_equation_cannon_calculator': typeof SimultaneousequationcannoncalculatorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/simultaneous_equation_cannon_calculator/': typeof SimultaneousequationcannoncalculatorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simultaneous_equation_cannon_calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simultaneous_equation_cannon_calculator'
  id: '__root__' | '/' | '/simultaneous_equation_cannon_calculator/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimultaneousequationcannoncalculatorIndexRoute: typeof SimultaneousequationcannoncalculatorIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimultaneousequationcannoncalculatorIndexRoute:
    SimultaneousequationcannoncalculatorIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/simultaneous_equation_cannon_calculator/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/simultaneous_equation_cannon_calculator/": {
      "filePath": "simultaneous_equation_cannon_calculator/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
